# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
#
platform :ios, '8.0'
use_frameworks!

workspace 'LightStepTestUI'

target 'LightStepTestUI' do
    pod 'lightstep', '~>2.0'
end
