# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
#
source 'https://github.com/CocoaPods/Specs.git'

install! 'cocoapods', :deterministic_uuids => false

workspace 'LightStepTestUI'

target 'LightStepTestUI' do
  platform :ios, '8.0'
  pod 'lightstep', :path => '../..'
end

target 'LightStepCocoaTestUI' do
  platform :macos, '10.11'
  pod 'lightstep', :path => '../..'
end

target 'LightStepUnitTests' do
  platform :ios, '8.0'
  pod 'lightstep', :path => '../..'
end
