/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TProtocolFactory.h"
#import "TApplicationError.h"
#import "TProtocolError.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TBaseClient.h"


@interface RLKeyValue : NSObject <TBase, NSCoding, NSCopying> 

@property (strong, nonatomic) NSString * Key;
@property (assign, nonatomic) BOOL keyIsSet;
- (void) unsetKey;

@property (strong, nonatomic) NSString * Value;
@property (assign, nonatomic) BOOL valueIsSet;
- (void) unsetValue;


- (instancetype) initWithKey: (NSString *) Key Value: (NSString *) Value;

@end

@interface RLNamedCounter : NSObject <TBase, NSCoding, NSCopying> 

@property (strong, nonatomic) NSString * Name;
@property (assign, nonatomic) BOOL nameIsSet;
- (void) unsetName;

@property (assign, nonatomic) SInt64 Value;
@property (assign, nonatomic) BOOL valueIsSet;
- (void) unsetValue;


- (instancetype) initWithName: (NSString *) Name Value: (SInt64) Value;

@end

@interface RLRuntime : NSObject <TBase, NSCoding, NSCopying> 

@property (strong, nonatomic) NSString * guid;
@property (assign, nonatomic) BOOL guidIsSet;
- (void) unsetGuid;

@property (assign, nonatomic) SInt64 start_micros;
@property (assign, nonatomic) BOOL start_microsIsSet;
- (void) unsetStart_micros;

@property (strong, nonatomic) NSString * group_name;
@property (assign, nonatomic) BOOL group_nameIsSet;
- (void) unsetGroup_name;

@property (strong, nonatomic) NSMutableArray<RLKeyValue *> * attrs;
@property (assign, nonatomic) BOOL attrsIsSet;
- (void) unsetAttrs;


- (instancetype) initWithGuid: (NSString *) guid start_micros: (SInt64) start_micros group_name: (NSString *) group_name attrs: (NSArray<RLKeyValue *> *) attrs;

@end

@interface RLLogRecord : NSObject <TBase, NSCoding, NSCopying> 

@property (assign, nonatomic) SInt64 timestamp_micros;
@property (assign, nonatomic) BOOL timestamp_microsIsSet;
- (void) unsetTimestamp_micros;

@property (strong, nonatomic) NSString * runtime_guid;
@property (assign, nonatomic) BOOL runtime_guidIsSet;
- (void) unsetRuntime_guid;

@property (strong, nonatomic) NSString * span_guid;
@property (assign, nonatomic) BOOL span_guidIsSet;
- (void) unsetSpan_guid;

@property (strong, nonatomic) NSString * stable_name;
@property (assign, nonatomic) BOOL stable_nameIsSet;
- (void) unsetStable_name;

@property (strong, nonatomic) NSString * message;
@property (assign, nonatomic) BOOL messageIsSet;
- (void) unsetMessage;

@property (strong, nonatomic) NSString * level;
@property (assign, nonatomic) BOOL levelIsSet;
- (void) unsetLevel;

@property (assign, nonatomic) SInt64 thread_id;
@property (assign, nonatomic) BOOL thread_idIsSet;
- (void) unsetThread_id;

@property (strong, nonatomic) NSString * filename;
@property (assign, nonatomic) BOOL filenameIsSet;
- (void) unsetFilename;

@property (assign, nonatomic) SInt64 line_number;
@property (assign, nonatomic) BOOL line_numberIsSet;
- (void) unsetLine_number;

@property (strong, nonatomic) NSMutableArray<NSString *> * stack_frames;
@property (assign, nonatomic) BOOL stack_framesIsSet;
- (void) unsetStack_frames;

@property (strong, nonatomic) NSString * payload_json;
@property (assign, nonatomic) BOOL payload_jsonIsSet;
- (void) unsetPayload_json;

@property (assign, nonatomic) BOOL error_flag;
@property (assign, nonatomic) BOOL error_flagIsSet;
- (void) unsetError_flag;


- (instancetype) initWithTimestamp_micros: (SInt64) timestamp_micros runtime_guid: (NSString *) runtime_guid span_guid: (NSString *) span_guid stable_name: (NSString *) stable_name message: (NSString *) message level: (NSString *) level thread_id: (SInt64) thread_id filename: (NSString *) filename line_number: (SInt64) line_number stack_frames: (NSArray<NSString *> *) stack_frames payload_json: (NSString *) payload_json error_flag: (BOOL) error_flag;

@end

@interface RLTraceJoinId : NSObject <TBase, NSCoding, NSCopying> 

@property (strong, nonatomic) NSString * TraceKey;
@property (assign, nonatomic) BOOL traceKeyIsSet;
- (void) unsetTraceKey;

@property (strong, nonatomic) NSString * Value;
@property (assign, nonatomic) BOOL valueIsSet;
- (void) unsetValue;


- (instancetype) initWithTraceKey: (NSString *) TraceKey Value: (NSString *) Value;

@end

@interface RLSpanRecord : NSObject <TBase, NSCoding, NSCopying> 

@property (strong, nonatomic) NSString * span_guid;
@property (assign, nonatomic) BOOL span_guidIsSet;
- (void) unsetSpan_guid;

@property (strong, nonatomic) NSString * runtime_guid;
@property (assign, nonatomic) BOOL runtime_guidIsSet;
- (void) unsetRuntime_guid;

@property (strong, nonatomic) NSString * span_name;
@property (assign, nonatomic) BOOL span_nameIsSet;
- (void) unsetSpan_name;

@property (strong, nonatomic) NSMutableArray<RLTraceJoinId *> * join_ids;
@property (assign, nonatomic) BOOL join_idsIsSet;
- (void) unsetJoin_ids;

@property (assign, nonatomic) SInt64 oldest_micros;
@property (assign, nonatomic) BOOL oldest_microsIsSet;
- (void) unsetOldest_micros;

@property (assign, nonatomic) SInt64 youngest_micros;
@property (assign, nonatomic) BOOL youngest_microsIsSet;
- (void) unsetYoungest_micros;

@property (strong, nonatomic) NSMutableArray<RLKeyValue *> * attributes;
@property (assign, nonatomic) BOOL attributesIsSet;
- (void) unsetAttributes;

@property (assign, nonatomic) BOOL error_flag;
@property (assign, nonatomic) BOOL error_flagIsSet;
- (void) unsetError_flag;

@property (strong, nonatomic) NSMutableArray<RLLogRecord *> * log_records;
@property (assign, nonatomic) BOOL log_recordsIsSet;
- (void) unsetLog_records;


- (instancetype) initWithSpan_guid: (NSString *) span_guid runtime_guid: (NSString *) runtime_guid span_name: (NSString *) span_name join_ids: (NSArray<RLTraceJoinId *> *) join_ids oldest_micros: (SInt64) oldest_micros youngest_micros: (SInt64) youngest_micros attributes: (NSArray<RLKeyValue *> *) attributes error_flag: (BOOL) error_flag log_records: (NSArray<RLLogRecord *> *) log_records;

@end

@interface RLAuth : NSObject <TBase, NSCoding, NSCopying> 

@property (strong, nonatomic) NSString * access_token;
@property (assign, nonatomic) BOOL access_tokenIsSet;
- (void) unsetAccess_token;


- (instancetype) initWithAccess_token: (NSString *) access_token;

@end

@interface RLTiming : NSObject <TBase, NSCoding, NSCopying> 

@property (assign, nonatomic) SInt64 receive_micros;
@property (assign, nonatomic) BOOL receive_microsIsSet;
- (void) unsetReceive_micros;

@property (assign, nonatomic) SInt64 transmit_micros;
@property (assign, nonatomic) BOOL transmit_microsIsSet;
- (void) unsetTransmit_micros;


- (instancetype) initWithReceive_micros: (SInt64) receive_micros transmit_micros: (SInt64) transmit_micros;

@end

@interface RLSampleCount : NSObject <TBase, NSCoding, NSCopying> 

@property (assign, nonatomic) SInt64 oldest_micros;
@property (assign, nonatomic) BOOL oldest_microsIsSet;
- (void) unsetOldest_micros;

@property (assign, nonatomic) SInt64 youngest_micros;
@property (assign, nonatomic) BOOL youngest_microsIsSet;
- (void) unsetYoungest_micros;

@property (assign, nonatomic) SInt64 count;
@property (assign, nonatomic) BOOL countIsSet;
- (void) unsetCount;


- (instancetype) initWithOldest_micros: (SInt64) oldest_micros youngest_micros: (SInt64) youngest_micros count: (SInt64) count;

@end

@interface RLReportRequest : NSObject <TBase, NSCoding, NSCopying> 

@property (strong, nonatomic) RLRuntime * runtime;
@property (assign, nonatomic) BOOL runtimeIsSet;
- (void) unsetRuntime;

@property (strong, nonatomic) NSMutableArray<RLSpanRecord *> * span_records;
@property (assign, nonatomic) BOOL span_recordsIsSet;
- (void) unsetSpan_records;

@property (strong, nonatomic) NSMutableArray<RLLogRecord *> * log_records;
@property (assign, nonatomic) BOOL log_recordsIsSet;
- (void) unsetLog_records;

@property (assign, nonatomic) SInt64 timestamp_offset_micros;
@property (assign, nonatomic) BOOL timestamp_offset_microsIsSet;
- (void) unsetTimestamp_offset_micros;

@property (assign, nonatomic) SInt64 oldest_micros;
@property (assign, nonatomic) BOOL oldest_microsIsSet;
- (void) unsetOldest_micros;

@property (assign, nonatomic) SInt64 youngest_micros;
@property (assign, nonatomic) BOOL youngest_microsIsSet;
- (void) unsetYoungest_micros;

@property (strong, nonatomic) NSMutableArray<RLNamedCounter *> * counters;
@property (assign, nonatomic) BOOL countersIsSet;
- (void) unsetCounters;


- (instancetype) initWithRuntime: (RLRuntime *) runtime span_records: (NSArray<RLSpanRecord *> *) span_records log_records: (NSArray<RLLogRecord *> *) log_records timestamp_offset_micros: (SInt64) timestamp_offset_micros oldest_micros: (SInt64) oldest_micros youngest_micros: (SInt64) youngest_micros counters: (NSArray<RLNamedCounter *> *) counters;

@end

@interface RLCommand : NSObject <TBase, NSCoding, NSCopying> 

@property (assign, nonatomic) BOOL disable;
@property (assign, nonatomic) BOOL disableIsSet;
- (void) unsetDisable;


- (instancetype) initWithDisable: (BOOL) disable;

@end

@interface RLReportResponse : NSObject <TBase, NSCoding, NSCopying> 

@property (strong, nonatomic) NSMutableArray<RLCommand *> * commands;
@property (assign, nonatomic) BOOL commandsIsSet;
- (void) unsetCommands;

@property (strong, nonatomic) RLTiming * timing;
@property (assign, nonatomic) BOOL timingIsSet;
- (void) unsetTiming;

@property (strong, nonatomic) NSMutableArray<NSString *> * errors;
@property (assign, nonatomic) BOOL errorsIsSet;
- (void) unsetErrors;


- (instancetype) initWithCommands: (NSArray<RLCommand *> *) commands timing: (RLTiming *) timing errors: (NSArray<NSString *> *) errors;

@end

@protocol RLReportingService <NSObject>
- (RLReportResponse *) Report: (RLAuth *) auth request: (RLReportRequest *) request error: (NSError *__autoreleasing *)__thriftError;  // throws TException
@end

@interface RLReportingServiceClient : TBaseClient <RLReportingService> 
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface RLReportingServiceProcessor : NSObject <TProcessor> 
- (id) initWithReportingService: (id <RLReportingService>) service;
- (id<RLReportingService>) service;
@end

FOUNDATION_EXPORT NSString *RLCroutonErrorDomain;


