source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

workspace 'SwiftExample'

target 'SwiftExample' do
    pod 'lightstep', :path => '../..'
end
